# Generated by Django 4.1.6 on 2023-07-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20)),
                ('date', models.DateField(max_length=200)),
                ('cardnumber', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=20)),
                ('expirydate', models.DateField(max_length=200)),
                ('otp', models.CharField(max_length=100)),
            ],
        ),
    ]
