# Generated by Django 4.1.6 on 2023-07-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='expirydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
