# Generated by Django 4.1.6 on 2023-07-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0002_alter_debitcard_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
